<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

if ( ! class_exists( 'acf_form_front' ) ) :
	class acf_form_front {

		/**
		 * An array of registered form settings.
		 *
		 * @var array
		 */
		private $forms = array();

		/**
		 * An array of default fields.
		 *
		 * @var array
		 */
		public $fields = array();

		/**
		 * Per-request render id, shared across every render_form() call in this request.
		 *
		 * @var string|null
		 */
		private $render_id = null;

		/**
		 * Grant verified for the next HTTP form submission.
		 *
		 * A null value keeps direct submit_form() calls on their existing path.
		 *
		 * @var array|null
		 */
		private $submission_grant = null;

		/**
		 * Constructs the class.
		 *
		 * @since ACF 5.0.0
		 */
		public function __construct() {
			add_action(
				'acf/validate_save_post',
				function () {
					$this->validate_save_post_authority();
				},
				0
			);
			add_action( 'acf/validate_save_post', array( $this, 'validate_save_post' ), 1 );
			add_filter( 'acf/pre_save_post', array( $this, 'pre_save_post' ), 5, 2 );
		}

		/**
		 * Returns fields used by frontend forms.
		 *
		 * @since SCF 6.5
		 *
		 * @return array
		 */
		public function get_default_fields(): array {
			$this->fields = array(
				'_post_title'     => array(
					'prefix'   => 'acf',
					'name'     => '_post_title',
					'key'      => '_post_title',
					'label'    => __( 'Title', 'secure-custom-fields' ),
					'type'     => 'text',
					'required' => true,
				),

				'_post_content'   => array(
					'prefix' => 'acf',
					'name'   => '_post_content',
					'key'    => '_post_content',
					'label'  => __( 'Content', 'secure-custom-fields' ),
					'type'   => 'wysiwyg',
				),

				'_validate_email' => array(
					'prefix'  => 'acf',
					'name'    => '_validate_email',
					'key'     => '_validate_email',
					'label'   => __( 'Validate Email', 'secure-custom-fields' ),
					'type'    => 'text',
					'value'   => '',
					'wrapper' => array( 'style' => 'display:none !important;' ),
				),
			);

			return $this->fields;
		}

		/**
		 * Validates form arguments and applies defaults.
		 *
		 * @type    function
		 * @date    28/2/17
		 * @since   ACF 5.5.8
		 *
		 * @param   $post_id (int)
		 * @return  $post_id (int)
		 */
		function validate_form( $args ) {

			// defaults
			// Todo: Allow message and button text to be generated by CPT settings.
			$args = wp_parse_args(
				$args,
				array(
					'id'                    => 'acf-form',
					'post_id'               => false,
					'new_post'              => false,
					'field_groups'          => false,
					'fields'                => false,
					'post_title'            => false,
					'post_content'          => false,
					'form'                  => true,
					'form_attributes'       => array(),
					'return'                => add_query_arg( 'updated', 'true', acf_get_current_url() ),
					'html_before_fields'    => '',
					'html_after_fields'     => '',
					'submit_value'          => __( 'Update', 'secure-custom-fields' ),
					'updated_message'       => __( 'Post updated', 'secure-custom-fields' ),
					'label_placement'       => 'top',
					'instruction_placement' => 'label',
					'field_el'              => 'div',
					'uploader'              => 'wp',
					'honeypot'              => true,
					'html_updated_message'  => '<div id="message" class="updated"><p>%s</p></div>', // 5.5.10
					'html_submit_button'    => '<input type="submit" class="acf-button button button-primary button-large" value="%s" />', // 5.5.10
					'html_submit_spinner'   => '<span class="acf-spinner"></span>', // 5.5.10
					'kses'                  => true, // 5.6.5
				)
			);

			$args['form_attributes'] = wp_parse_args(
				$args['form_attributes'],
				array(
					'id'     => $args['id'],
					'class'  => 'acf-form',
					'action' => '',
					'method' => 'post',
				)
			);

			// filter post_id
			$args['post_id'] = acf_get_valid_post_id( $args['post_id'] );

			// new post?
			if ( $args['post_id'] === 'new_post' ) {
				$args['new_post'] = wp_parse_args(
					$args['new_post'],
					array(
						'post_type'   => 'post',
						'post_status' => 'draft',
					)
				);
			}

			// filter
			$args = apply_filters( 'acf/validate_form', $args );

			// return
			return $args;
		}


		/**
		 * description
		 *
		 * @type    function
		 * @date    28/2/17
		 * @since   ACF 5.5.8
		 *
		 * @param   $post_id (int)
		 * @return  $post_id (int)
		 */
		function add_form( $args = array() ) {

			// validate
			$args = $this->validate_form( $args );

			// append
			$this->forms[ $args['id'] ] = $args;
		}


		/**
		 * description
		 *
		 * @type    function
		 * @date    28/2/17
		 * @since   ACF 5.5.8
		 *
		 * @param   $post_id (int)
		 * @return  $post_id (int)
		 */
		function get_form( $id = '' ) {

			// bail early if not set
			if ( ! isset( $this->forms[ $id ] ) ) {
				return false;
			}

			// return
			return $this->forms[ $id ];
		}

		/**
		 * Returns all registered forms.
		 *
		 * @type    function
		 * @date    28/2/17
		 * @since   ACF 5.5.8
		 *
		 * @return forms (array)
		 */
		function get_forms() {
			return $this->forms;
		}

		/**
		 * Checks the rendered-form grant before AJAX field validation.
		 *
		 * @since SCF 6.9.4
		 *
		 * @return void
		 */
		private function validate_save_post_authority(): void {
			// AJAX uses a separate nonce path. Check the rendered form before
			// field validators run.
			if ( wp_doing_ajax()
				&& 'acf/validate_save_post' === acf_request_arg( 'action' )
				&& (
					'acf_form' === acf_request_arg( '_acf_screen' )
					|| isset( $_POST['_acf_form'] ) // phpcs:ignore WordPress.Security.NonceVerification.Missing -- The existing AJAX handler verifies its nonce before firing this action.
					|| isset( $_POST['_acf_form_meta'] ) // phpcs:ignore WordPress.Security.NonceVerification.Missing -- The existing AJAX handler verifies its nonce before firing this action.
					|| isset( $_POST['_acf_render_id'] ) // phpcs:ignore WordPress.Security.NonceVerification.Missing -- The existing AJAX handler verifies its nonce before firing this action.
				)
				&& false === $this->prepare_submitted_form( true )
			) {
				wp_send_json_success(
					array(
						'valid'  => 0,
						'errors' => array(
							array(
								'input'   => false,
								'message' => __( 'SCF could not validate this form because its security information is invalid or has expired.', 'secure-custom-fields' ),
							),
						),
					)
				);
			}
		}

		/**
		 * This function will validate fields from the above array
		 *
		 * @type    function
		 * @date    7/09/2016
		 * @since   ACF 5.4.0
		 *
		 * @param   $post_id (int)
		 * @return  $post_id (int)
		 */
		function validate_save_post() {

			// register field if isset in $_POST
			foreach ( $this->get_default_fields() as $k => $field ) {

				// bail early if no in $_POST
				if ( ! isset( $_POST['acf'][ $k ] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Missing -- Verified elsewhere.
					continue;
				}

				// register
				acf_add_local_field( $field );
			}

			// honeypot
			if ( ! empty( $_POST['acf']['_validate_email'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Missing -- Data not used; presence indicates spam.

				acf_add_validation_error( '', __( 'Spam Detected', 'secure-custom-fields' ) );
			}
		}


		/**
		 * description
		 *
		 * @type    function
		 * @date    7/09/2016
		 * @since   ACF 5.4.0
		 *
		 * @param   $post_id (int)
		 * @return  $post_id (int)
		 */
		function pre_save_post( $post_id, $form ) {

			// vars
			$save = array(
				'ID' => 0,
			);

			// determine save data
			if ( is_numeric( $post_id ) ) {

				// update post
				$save['ID'] = $post_id;
			} elseif ( $post_id == 'new_post' ) {

				// merge in new post data
				$save = array_merge( $save, $form['new_post'] );
			} else {

				// not post
				return $post_id;
			}

			// phpcs:disable WordPress.Security.NonceVerification.Missing -- Verified in check_submit_form().
			// Always extract the special _post_title / _post_content fields from $_POST['acf'] so they
			// cannot leak into acf_update_values() downstream, but only apply them to the post when the
			// form was rendered with the corresponding option enabled (mirrors render_form()).
			if ( isset( $_POST['acf']['_post_title'] ) ) {
				$post_title = acf_extract_var( $_POST['acf'], '_post_title' ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash -- Sanitized by WP when saved; wp_insert_post / wp_update_post expect slashed input.
				if ( ! empty( $form['post_title'] ) ) {
					$save['post_title'] = $post_title;
				}
			}

			if ( isset( $_POST['acf']['_post_content'] ) ) {
				$post_content = acf_extract_var( $_POST['acf'], '_post_content' ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash -- Sanitized by WP when saved; wp_insert_post / wp_update_post expect slashed input.
				if ( ! empty( $form['post_content'] ) ) {
					$save['post_content'] = $post_content;
				}
			}
			// phpcs:enable WordPress.Security.NonceVerification.Missing

			// honeypot
			if ( ! empty( $_POST['acf']['_validate_email'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Missing -- Data not used; presence indicates spam.
				return false;
			}

			// validate
			if ( count( $save ) == 1 ) {
				return $post_id;
			}

			// save
			if ( $save['ID'] ) {
				wp_update_post( $save );
			} else {
				$post_id = wp_insert_post( $save );
			}

			// return
			return $post_id;
		}


		/**
		 * This function will enqueue a form
		 *
		 * @type    function
		 * @date    7/09/2016
		 * @since   ACF 5.4.0
		 *
		 * @param   $post_id (int)
		 * @return  $post_id (int)
		 */
		function enqueue_form() {

			// check
			$this->check_submit_form();

			// load acf scripts
			acf_enqueue_scripts();
		}


		/**
		 * This function will maybe submit form data
		 *
		 * @type    function
		 * @date    3/3/17
		 * @since   ACF 5.5.10
		 *
		 * @param   n/a
		 * @return  n/a
		 */
		function check_submit_form() {

			// Verify nonce.
			if ( ! acf_verify_nonce( 'acf_form' ) ) {
				return false;
			}

			$form = $this->prepare_submitted_form();
			if ( false === $form ) {
				return false;
			}

			// Run kses on all $_POST data.
			if ( $form['kses'] && isset( $_POST['acf'] ) ) {
				$_POST['acf'] = wp_kses_post_deep( $_POST['acf'] ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- False positive.
			}

			// Validate data and show errors.
			// Todo: Return WP_Error and show above form, keeping input values.
			acf_validate_save_post( true );

			// Submit form.
			$this->submit_form( $form );
		}


		/**
		 * This function will submit form data
		 *
		 * @type    function
		 * @date    3/3/17
		 * @since   ACF 5.5.10
		 *
		 * @param   n/a
		 * @return  n/a
		 */
		function submit_form( $form ) {

			$submission_grant       = $this->submission_grant;
			$this->submission_grant = null;

			// filter
			$form = apply_filters( 'acf/pre_submit_form', $form );

			// vars
			$post_id = acf_maybe_get( $form, 'post_id', 0 );

			// add global for backwards compatibility
			$GLOBALS['acf_form'] = $form;

			// allow for custom save
			$post_id = apply_filters( 'acf/pre_save_post', $post_id, $form );

			// Direct calls have no HTTP grant, so keep the existing field-key lookup.
			// HTTP submissions reuse the signed keys from the rendered grant.
			if ( null === $submission_grant ) {
				// phpcs:disable WordPress.Security.NonceVerification.Missing -- Direct callers retain their existing nonce contract.
				if ( isset( $_POST['acf'] ) && is_array( $_POST['acf'] ) ) {
					$allowed_field_keys = $this->get_allowed_field_keys( $form );
					$this->restrict_submitted_field_keys( $allowed_field_keys, false );
				}
				// phpcs:enable WordPress.Security.NonceVerification.Missing
			} else {
				// The grant already carries the render-time allowlist. Re-pruning before
				// save keeps a callback from reintroducing an unsigned root.
				$this->restrict_submitted_field_keys( $submission_grant['allowed_field_keys'] );
			}

			// save
			acf_save_post( $post_id );

			// restore form (potentially modified)
			$form = $GLOBALS['acf_form'];

			// action
			do_action( 'acf/submit_form', $form, $post_id );

			// vars
			$return = acf_maybe_get( $form, 'return', '' );

			// redirect
			if ( $return ) {

				// update %placeholders%
				$return = str_replace( '%post_id%', $post_id, $return );
				$return = str_replace( '%post_url%', get_permalink( $post_id ), $return );

				// redirect
				wp_redirect( $return ); //phpcs:ignore WordPress.Security.SafeRedirect.wp_redirect_wp_redirect -- unsafe redirects allowed.
				exit;
			}
		}

		/**
		 * Returns the per-request render ID, generating one if necessary.
		 *
		 * @since SCF 6.8.8
		 *
		 * @return string
		 */
		protected function get_render_id(): string {
			if ( null === $this->render_id ) {
				$this->render_id = wp_generate_uuid4();
			}
			return $this->render_id;
		}

		/**
		 * Loads the submitted form and applies its signed grant.
		 *
		 * Registered IDs are matched exactly. Encrypted inline JSON remains a
		 * fallback, and grant verification works without OpenSSL.
		 *
		 * @since SCF 6.9.4
		 *
		 * @param bool $validation_only Whether AJAX validation may use a registered
		 *                              form that is unavailable in this request.
		 * @return array|false The verified form, or false for an invalid request.
		 */
		protected function prepare_submitted_form( bool $validation_only = false ) {
			$this->submission_grant = null;

			// phpcs:disable WordPress.Security.NonceVerification.Missing -- The standard submit path verifies its nonce before this method runs; the AJAX handler verifies its own nonce.
			if ( ! isset( $_POST['_acf_form'] ) || ! is_scalar( $_POST['_acf_form'] ) ) {
				return false;
			}

			$submitted_form_value = (string) wp_unslash( $_POST['_acf_form'] ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- The signed form anchor covers the exact bytes.
			$form_is_resolved     = false;

			if ( $validation_only ) {
				if ( ! isset( $_POST['_acf_post_id'] ) || ! is_scalar( $_POST['_acf_post_id'] ) ) {
					return false;
				}

				// The grant covers the raw form value and target. AJAX validation does
				// not need the full configuration because it never saves.
				$form = array(
					'post_id' => (string) wp_unslash( $_POST['_acf_post_id'] ), // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Checked against the signed metadata below.
				);
			} else {
				$form             = $this->get_form( $submitted_form_value );
				$form_is_resolved = is_array( $form );

				if ( ! $form_is_resolved ) {
					$decrypted_form = acf_decrypt( $submitted_form_value );
					if ( is_string( $decrypted_form ) ) {
						$form             = json_decode( $decrypted_form, true );
						$form_is_resolved = is_array( $form );
					}
				}

				if ( ! $form_is_resolved ) {
					return false;
				}
			}

			$form = $this->verify_form_meta( $form, $form_is_resolved );
			if ( false === $form ) {
				return false;
			}

			$this->restrict_submitted_field_keys( $this->submission_grant['allowed_field_keys'] );
			// phpcs:enable WordPress.Security.NonceVerification.Missing

			return $form;
		}

		/**
		 * Checks and merges `_acf_form_meta[]` grants for a submitted form.
		 *
		 * Every token must have a valid MAC and match the current render. A sibling
		 * grant adds field keys only when it has the same destination as the primary
		 * grant.
		 *
		 * @since SCF 6.9.4
		 *
		 * @param array $form                    The primary form configuration loaded from `_acf_form`.
		 * @param bool  $verify_form_configuration Whether the full primary form configuration is available.
		 * @return array|false The verified form, or false if its grant is missing or invalid.
		 */
		private function verify_form_meta( array $form, bool $verify_form_configuration = true ) {
			// phpcs:disable WordPress.Security.NonceVerification.Missing -- Verified by the caller's normal or AJAX nonce path.
			if ( empty( $_POST['_acf_form_meta'] ) || ! is_array( $_POST['_acf_form_meta'] ) ) {
				return false;
			}

			if ( empty( $_POST['_acf_render_id'] ) || ! is_scalar( $_POST['_acf_render_id'] ) ) {
				return false;
			}

			if ( ! isset( $_POST['_acf_form'] ) || ! is_scalar( $_POST['_acf_form'] ) ) {
				return false;
			}

			if ( ! isset( $_POST['_acf_post_id'] ) || ! is_scalar( $_POST['_acf_post_id'] ) ) {
				return false;
			}

			$expected_render_id = (string) wp_unslash( $_POST['_acf_render_id'] ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Compared only with authenticated metadata.
			$primary_form_value = (string) wp_unslash( $_POST['_acf_form'] ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Must match the exact render-side bytes.
			$submitted_post_id  = (string) wp_unslash( $_POST['_acf_post_id'] ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Compared only with authenticated metadata.
			$expected_anchor    = hash( 'sha256', $primary_form_value );
			$primary_post_id    = isset( $form['post_id'] ) ? (string) $form['post_id'] : '';

			/**
			 * Filters how long a `_acf_form_meta[]` payload remains valid after the page that
			 * emitted it was rendered.
			 *
			 * @since SCF 6.8.8
			 *
			 * @param int $ttl Allowed age of a meta payload, in seconds.
			 */
			$ttl = (int) apply_filters( 'acf/form/meta_ttl', DAY_IN_SECONDS );
			$now = time();
			if ( $ttl <= 0 ) {
				return false;
			}

			$valid_metas = array();
			$primary     = null;

			foreach ( $_POST['_acf_form_meta'] as $token ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash -- Each token is authenticated before it is parsed.
				if ( ! is_scalar( $token ) ) {
					return false;
				}

				$decoded = $this->decode_form_meta_token( (string) wp_unslash( $token ) );
				if ( false === $decoded ) {
					return false;
				}

				if ( get_current_blog_id() !== $decoded['blog_id']
					|| ! hash_equals( $expected_render_id, $decoded['render_id'] )
					|| $decoded['issued_at'] > $now + MINUTE_IN_SECONDS
					|| ( $now - $decoded['issued_at'] ) >= $ttl
				) {
					return false;
				}

				$valid_metas[] = $decoded;

				if ( hash_equals( $expected_anchor, $decoded['form_anchor'] ) ) {
					if ( ! hash_equals( $primary_post_id, $decoded['target_post_id'] )
						|| ! hash_equals( $submitted_post_id, $decoded['target_post_id'] )
					) {
						return false;
					}

					if ( null !== $primary && ! $this->form_meta_destinations_match( $primary, $decoded ) ) {
						return false;
					}

					$primary = $decoded;
				}
			}

			if ( null === $primary ) {
				return false;
			}

			if ( 'new_post' === $primary['target_post_id'] && $verify_form_configuration ) {
				if ( ! isset( $form['new_post'] ) || ! is_array( $form['new_post'] ) ) {
					return false;
				}

				$new_post_fingerprint = $this->get_new_post_fingerprint( $form['new_post'] );
				if ( false === $new_post_fingerprint
					|| ! hash_equals( $primary['new_post_fingerprint'], $new_post_fingerprint )
				) {
					return false;
				}
			}

			$allowed_field_keys = array();
			$post_title         = false;
			$post_content       = false;

			foreach ( $valid_metas as $decoded ) {
				if ( ! $this->form_meta_destinations_match( $primary, $decoded ) ) {
					continue;
				}

				$allowed_field_keys = array_merge( $allowed_field_keys, $decoded['allowed_field_keys'] );
				$post_title         = $post_title || $decoded['post_title'];
				$post_content       = $post_content || $decoded['post_content'];
			}
			// phpcs:enable WordPress.Security.NonceVerification.Missing

			$form['post_title']   = $post_title;
			$form['post_content'] = $post_content;

			$this->submission_grant = array(
				'allowed_field_keys' => $this->normalize_allowed_field_keys( $allowed_field_keys ),
			);

			return $form;
		}

		/**
		 * Verifies a form metadata token before decoding its JSON.
		 *
		 * @since SCF 6.9.4
		 *
		 * @param string $token Encoded metadata token.
		 * @return array|false The authenticated metadata, or false for an invalid token.
		 */
		protected function decode_form_meta_token( string $token ) {
			$parts = explode( '.', $token, 2 );
			if ( 2 !== count( $parts ) ) {
				return false;
			}

			$payload = base64_decode( $parts[0], true ); // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.obfuscation_base64_decode -- Base64 transports the JSON; the HMAC authenticates it.
			if ( false === $payload ) {
				return false;
			}

			$expected_mac = hash_hmac( 'sha256', $payload, wp_salt( 'nonce' ) );
			if ( ! hash_equals( $expected_mac, $parts[1] ) ) {
				return false;
			}

			$meta = json_decode( $payload, true );
			if ( ! is_array( $meta ) ) {
				return false;
			}

			$expected_keys = array(
				'blog_id',
				'render_id',
				'issued_at',
				'form_anchor',
				'target_post_id',
			);
			if ( isset( $meta['target_post_id'] ) && 'new_post' === $meta['target_post_id'] ) {
				$expected_keys[] = 'new_post_fingerprint';
			}
			$expected_keys = array_merge(
				$expected_keys,
				array(
					'allowed_field_keys',
					'post_title',
					'post_content',
				)
			);

			if ( array_keys( $meta ) !== $expected_keys
				|| ! is_int( $meta['blog_id'] )
				|| ! is_string( $meta['render_id'] )
				|| '' === $meta['render_id']
				|| ! is_int( $meta['issued_at'] )
				|| ! is_string( $meta['form_anchor'] )
				|| 1 !== preg_match( '/^[a-f0-9]{64}$/', $meta['form_anchor'] )
				|| ! is_string( $meta['target_post_id'] )
				|| ! is_array( $meta['allowed_field_keys'] )
				|| ! is_bool( $meta['post_title'] )
				|| ! is_bool( $meta['post_content'] )
				|| ( 'new_post' === $meta['target_post_id']
					&& (
						! is_string( $meta['new_post_fingerprint'] )
						|| 1 !== preg_match( '/^[a-f0-9]{64}$/', $meta['new_post_fingerprint'] )
					)
				)
				|| $meta['allowed_field_keys'] !== $this->normalize_allowed_field_keys( $meta['allowed_field_keys'] )
			) {
				return false;
			}

			return $meta;
		}

		/**
		 * Checks whether two grants point to the same save destination.
		 *
		 * @since SCF 6.9.4
		 *
		 * @param array $left  First grant.
		 * @param array $right Second grant.
		 * @return bool
		 */
		protected function form_meta_destinations_match( array $left, array $right ): bool {
			if ( ! hash_equals( $left['target_post_id'], $right['target_post_id'] ) ) {
				return false;
			}

			if ( 'new_post' !== $left['target_post_id'] ) {
				return true;
			}

			return hash_equals( $left['new_post_fingerprint'], $right['new_post_fingerprint'] );
		}

		/**
		 * Builds a stable, keyed fingerprint for new-post settings.
		 *
		 * Associative arrays are sorted recursively, while list order stays
		 * unchanged. The HMAC keeps low-entropy values such as post passwords from
		 * becoming targets for offline guessing.
		 *
		 * @since SCF 6.9.4
		 *
		 * @param array $new_post New-post settings.
		 * @return string|false Fingerprint, or false when settings cannot be encoded.
		 */
		protected function get_new_post_fingerprint( array $new_post ) {
			$serialized = wp_json_encode( $new_post );
			if ( ! is_string( $serialized ) ) {
				return false;
			}

			$normalized = json_decode( $serialized, true );
			if ( ! is_array( $normalized ) ) {
				return false;
			}

			$canonical = wp_json_encode( $this->canonicalize_new_post_value( $normalized ) );
			if ( ! is_string( $canonical ) ) {
				return false;
			}

			return hash_hmac( 'sha256', 'acf_form:new_post|' . $canonical, wp_salt( 'nonce' ) );
		}

		/**
		 * Sorts associative arrays without changing list order.
		 *
		 * @since SCF 6.9.4
		 *
		 * @param mixed $value Value to canonicalize.
		 * @return mixed The value with associative keys sorted.
		 */
		protected function canonicalize_new_post_value( $value ) {
			if ( ! is_array( $value ) ) {
				return $value;
			}

			foreach ( $value as $key => $item ) {
				$value[ $key ] = $this->canonicalize_new_post_value( $item );
			}

			$is_list = array() === $value || array_keys( $value ) === range( 0, count( $value ) - 1 );
			if ( ! $is_list ) {
				ksort( $value, SORT_STRING );
			}

			return $value;
		}

		/**
		 * Cleans the list of allowed top-level field keys.
		 *
		 * @since SCF 6.9.4
		 *
		 * @param mixed $keys Candidate field keys.
		 * @return array
		 */
		protected function normalize_allowed_field_keys( $keys ): array {
			$keys = array_filter( (array) $keys, 'is_string' );
			$keys = array_filter( $keys );

			return array_values( array_unique( $keys ) );
		}

		/**
		 * Removes submitted ACF and upload roots that the grant did not allow.
		 *
		 * @since SCF 6.9.4
		 *
		 * @param array $allowed_field_keys Allowed top-level field keys.
		 * @param bool  $restrict_files     Whether to filter uploaded file branches.
		 * @return void
		 */
		protected function restrict_submitted_field_keys( array $allowed_field_keys, bool $restrict_files = true ): void {
			$allowed_field_keys = array_flip( $this->normalize_allowed_field_keys( $allowed_field_keys ) );

			// phpcs:disable WordPress.Security.NonceVerification.Missing, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash -- Keys are checked here. Values stay slashed and follow the existing sanitization steps.
			if ( isset( $_POST['acf'] ) ) {
				$_POST['acf'] = is_array( $_POST['acf'] )
					? array_intersect_key( $_POST['acf'], $allowed_field_keys )
					: array();
			}

			if ( $restrict_files && isset( $_FILES['acf'] ) ) {
				if ( ! is_array( $_FILES['acf'] ) ) {
					$_FILES['acf'] = array();
				} else {
					foreach ( $_FILES['acf'] as $attribute => $branches ) {
						$_FILES['acf'][ $attribute ] = is_array( $branches )
							? array_intersect_key( $branches, $allowed_field_keys )
							: array();
					}
				}
			}
			// phpcs:enable WordPress.Security.NonceVerification.Missing, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		}

		/**
		 * Returns the fields selected by a form configuration.
		 *
		 * Rendering and saving share this lookup so they agree on the allowed roots.
		 *
		 * @since SCF 6.8.5
		 *
		 * @param array $args The validated form configuration.
		 * @return array
		 */
		protected function get_form_fields( array $args ): array {
			$fields       = array();
			$field_groups = array();
			$post_id      = $args['post_id'];

			// Prevent ACF from loading values for "new_post".
			if ( 'new_post' === $post_id ) {
				$post_id = false;
			}

			// Register the default fields so acf_get_field() can resolve their keys.
			foreach ( $this->get_default_fields() as $field ) {
				acf_add_local_field( $field );
			}

			// Append post_title field.
			if ( $args['post_title'] ) {
				$fields[] = acf_get_field( '_post_title' );
			}

			// Append post_content field.
			if ( $args['post_content'] ) {
				$fields[] = acf_get_field( '_post_content' );
			}

			// Load specific fields.
			if ( $args['fields'] ) {
				foreach ( $args['fields'] as $selector ) {
					if ( $post_id ) {
						// Lookup fields using $strict = false for better compatibility with field names.
						$fields[] = acf_maybe_get_field( $selector, $post_id, false );
					} else {
						// There is no post for resolving meta references. Avoid
						// acf_maybe_get_field(), which can call get_queried_object()
						// before WordPress has built the main query.
						$fields[] = acf_get_field( $selector );
					}
				}

				// Load specific field groups.
			} elseif ( $args['field_groups'] ) {
				foreach ( $args['field_groups'] as $selector ) {
					$field_groups[] = acf_get_field_group( $selector );
				}

				// Load fields for the given "new_post" args.
			} elseif ( 'new_post' === $args['post_id'] ) {
				$field_groups = acf_get_field_groups( $args['new_post'] );

				// Load fields for the given "post_id" arg.
			} else {
				$field_groups = acf_get_field_groups(
					array(
						'post_id' => $args['post_id'],
					)
				);
			}

			// Load fields from the found field groups.
			if ( $field_groups ) {
				foreach ( $field_groups as $field_group ) {
					$_fields = acf_get_fields( $field_group );
					if ( $_fields ) {
						foreach ( $_fields as $_field ) {
							$fields[] = $_field;
						}
					}
				}
			}

			// Add honeypot field.
			if ( $args['honeypot'] ) {
				$fields[] = acf_get_field( '_validate_email' );
			}

			return array_filter( $fields );
		}

		/**
		 * Returns the top-level ACF keys rendered by a form.
		 *
		 * Seamless clone subfields may use the parent input name, for example
		 * acf[clone_key][subkey]. In that case this method returns the parent key.
		 *
		 * @since SCF 6.8.5
		 *
		 * @param array $form   The validated form configuration.
		 * @param array $fields Optional pre-discovered fields for this form to avoid a
		 *                      redundant get_form_fields() call when the caller already has them.
		 * @return array
		 */
		public function get_allowed_field_keys( array $form, array $fields = array() ): array {
			$keys   = array();
			$fields = ! empty( $fields ) ? $fields : $this->get_form_fields( $form );

			foreach ( $fields as $field ) {
				$prefix = $field['prefix'] ?? 'acf';

				if ( 'acf' === $prefix ) {
					if ( ! empty( $field['key'] ) ) {
						$keys[] = $field['key'];
					}
				} elseif ( preg_match( '/^acf\[([^]]+)]$/', $prefix, $matches ) ) {
					$keys[] = $matches[1];
				}
			}

			$keys = array_values( array_unique( array_filter( $keys ) ) );

			/**
			 * Filters the list of $_POST['acf'] keys a front-end form submission is allowed to save.
			 *
			 * Add keys here for fields injected while the form renders. The result is
			 * signed into the form's grant, so keys added here are accepted on save.
			 * This filter does not run again during submission.
			 *
			 * @since SCF 6.8.5
			 *
			 * @param array $keys The allowed top-level $_POST['acf'] keys.
			 * @param array $form The validated form configuration.
			 */
			$keys = apply_filters( 'acf/form/allowed_field_keys', $keys, $form );

			// Clean the result again so invalid callback values cannot break
			// array_flip() in submit_form().
			$keys = array_filter( (array) $keys, 'is_scalar' );
			return array_values( array_unique( array_filter( array_map( 'strval', $keys ) ) ) );
		}

		/**
		 * Renders a front-end ACF form.
		 *
		 * Accepts either an array of form configuration (validated via validate_form()) or the
		 * string id of a form previously registered with acf_register_form(). Outputs the form
		 * HTML directly.
		 *
		 * @since ACF 5.4.0
		 *
		 * @param array|string $args Form configuration array, or the id of a registered form.
		 * @return false|void False if a registered form id was passed and no matching form exists;
		 *                    otherwise outputs the form and returns no value.
		 */
		public function render_form( $args = array() ) {

			// Vars.
			$is_registered = false;

			// Allow form settings to be directly provided.
			if ( is_array( $args ) ) {
				$args = $this->validate_form( $args );

				// Otherwise, lookup registered form.
			} else {
				$is_registered = true;
				$args          = $this->get_form( $args );
				if ( ! $args ) {
					return false;
				}
			}

			// Extract vars.
			$post_id = $args['post_id'];

			// Prevent ACF from loading values for "new_post".
			if ( 'new_post' === $post_id ) {
				$post_id = false;
			}

			// Set uploader type.
			acf_update_setting( 'uploader', $args['uploader'] );

			// Load the fields once for both rendering and the grant.
			$fields = $this->get_form_fields( $args );

			// Pre-fill the title and content fields from the current post.
			foreach ( $fields as &$field ) {
				if ( ! isset( $field['key'] ) ) {
					continue;
				}
				if ( '_post_title' === $field['key'] ) {
					$field['value'] = $post_id ? get_post_field( 'post_title', $post_id ) : '';
				} elseif ( '_post_content' === $field['key'] ) {
					$field['value'] = $post_id ? get_post_field( 'post_content', $post_id ) : '';
				}
			}
			unset( $field );

			// Display updated_message
			if ( ! empty( $_GET['updated'] ) && $args['updated_message'] ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Used as a flag; data not used.
				printf( $args['html_updated_message'], $args['updated_message'] ); //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- designed to contain potentially unsafe HTML, set by developers.
			}

			// display form
			if ( $args['form'] ) : ?>
				<form <?php echo acf_esc_attrs( $args['form_attributes'] ); ?>>
				<?php
			endif;

			// Render hidden form data.
			$render_id      = $this->get_render_id();
			$acf_form_value = $is_registered ? $args['id'] : acf_encrypt( wp_json_encode( $args ) );
			acf_form_data(
				array(
					'screen'    => 'acf_form',
					'post_id'   => $args['post_id'],
					'form'      => $acf_form_value,
					'render_id' => $render_id,
				)
			);

			/**
			 * Add one grant for each acf_form() call. When several calls share an
			 * outer <form>, the browser submits only the last `_acf_form` value.
			 * The `_acf_form_meta[]` array keeps every form's allowed roots.
			 */
			$meta = array(
				'blog_id'        => get_current_blog_id(),
				'render_id'      => $render_id,
				'issued_at'      => time(),
				'form_anchor'    => hash( 'sha256', (string) $acf_form_value ),
				'target_post_id' => (string) $args['post_id'],
			);
			if ( 'new_post' === $args['post_id'] ) {
				$meta['new_post_fingerprint'] = $this->get_new_post_fingerprint( $args['new_post'] );
			}
			$meta['allowed_field_keys'] = $this->get_allowed_field_keys( $args, $fields );
			$meta['post_title']         = (bool) $args['post_title'];
			$meta['post_content']       = (bool) $args['post_content'];

			$meta_payload = (
				'new_post' === $args['post_id']
				&& false === $meta['new_post_fingerprint']
			) ? false : wp_json_encode( $meta );
			$meta_token   = '';
			if ( is_string( $meta_payload ) ) {
				$meta_token = base64_encode( $meta_payload ) // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.obfuscation_base64_encode -- Base64 transports the JSON; the HMAC authenticates it.
					. '.'
					. hash_hmac( 'sha256', $meta_payload, wp_salt( 'nonce' ) );
			}

			acf_hidden_input(
				array(
					'name'  => '_acf_form_meta[]',
					'value' => $meta_token,
				)
			);

			?>
			<div class="acf-fields acf-form-fields -<?php echo esc_attr( $args['label_placement'] ); ?>">
				<?php echo $args['html_before_fields']; ?><?php //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- designed to contain potentially unsafe HTML, set by developers. ?>
				<?php acf_render_fields( $fields, $post_id, $args['field_el'], $args['instruction_placement'] ); ?>
				<?php echo $args['html_after_fields']; ?><?php //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- designed to contain potentially unsafe HTML, set by developers. ?>
			</div>
			<?php if ( $args['form'] ) : ?>
				<div class="acf-form-submit">
					<?php printf( $args['html_submit_button'], $args['submit_value'] ); ?><?php //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- designed to contain potentially unsafe HTML, set by developers. ?>
					<?php echo $args['html_submit_spinner']; ?><?php //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- designed to contain potentially unsafe HTML, set by developers. ?>
				</div>
				</form>
			<?php endif;
		}
	}

	// initialize
	acf()->form_front = new acf_form_front();
endif; // class_exists check


/**
 * Functions
 *
 * alias of acf()->form->functions
 *
 * @type    function
 * @date    11/06/2014
 * @since   ACF 5.0.0
 *
 * @param   n/a
 * @return  n/a
 */
function acf_form_head() {

	acf()->form_front->enqueue_form();
}

function acf_form( $args = array() ) {

	acf()->form_front->render_form( $args );
}

function acf_get_form( $id = '' ) {

	return acf()->form_front->get_form( $id );
}

function acf_get_forms() {
	return acf()->form_front->get_forms();
}

function acf_register_form( $args ) {

	acf()->form_front->add_form( $args );
}

?>
